name: fossa-analyze

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fossa-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Fossa CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash   
        